import os

file_path = "/home/kali/Desktop/projects/Django/Kafe/frontend/src/pages/Admin.jsx"
with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    "Yangi": "Новый",
    "Tayyorlanmoqda": "Готовится",
    "Tayyor": "Готов",
    "Yo\\'lda": "В пути",
    "Yetkazib berildi": "Доставлен",
    "Bekor qilingan": "Отменен",
    "Ofitsant buyurtmalarini yuklashda xatolik": "Ошибка при загрузке заказов официанта",
    "Tarixni yuklashda xatolik: ": "Ошибка при загрузке истории: ",
    "Ofitsant uchun default foiz saqlandi!": "Процент по умолчанию для официанта сохранен!",
    "Saqlashda xatolik: ": "Ошибка при сохранении: ",
    "Buyurtma #": "Заказ #",
    " ga ": " на ",
    "% xizmat haqi qo'shildi!": "% плата за обслуживание добавлена!",
    "Foiz qo'shishda xatolik: ": "Ошибка при добавлении процента: ",
    "Chek #": "Чек #",
    " printerga yuborildi!": " отправлен на принтер!",
    "Xatolik: ": "Ошибка: ",
    "'Nomi'": "'Название'",
    "Kategoriya qo'shishda xatolik": "Ошибка при добавлении категории",
    "'Kategoriya'": "'Категория'",
    "Mahsulot saqlashda xatolik": "Ошибка при сохранении продукта",
    "'Ism'": "'Имя'",
    "Xodim qo'shishda xatolik": "Ошибка при добавлении сотрудника",
    "Rasm yuklashda xatolik": "Ошибка при загрузке изображения",
    "Haqiqatan ham bu xodimni o'chirmoqchimisiz?": "Вы действительно хотите удалить этого сотрудника?",
    "Xodimni o'chirishda xatolik": "Ошибка при удалении сотрудника",
    "Haqiqatan ham bu kategoriyani o'chirmoqchimisiz? Ichidagi mahsulotlar ham o'chishi mumkin!": "Вы действительно хотите удалить эту категорию? Продукты внутри также могут быть удалены!",
    "Kategoriyani o'chirishda xatolik. Avval undagi mahsulotlarni o'chirib ko'ring.": "Ошибка при удалении категории. Сначала попробуйте удалить продукты в ней.",
    "Olib tashlashga ishonchingiz komilmi?": "Вы уверены, что хотите удалить?",
    "Xatolik": "Ошибка",
    "Sozlamalar saqlandi": "Настройки сохранены",
    "Hatolik: ": "Ошибка: ",
    "Saqlab bo'lmadi": "Не удалось сохранить",
    "Summani kiritish majburiy": "Необходимо ввести сумму",
    "Xarajat qo'shishda xatolik: ": "Ошибка при добавлении расхода: ",
    "Stol qo'shishda xatolik": "Ошибка при добавлении стола",
    "Rostdan ham bu stolni o'chirmoqchimisiz?": "Вы действительно хотите удалить этот стол?",
    "Buyurtma ma'lumotlarini yuklashda xatolik": "Ошибка при загрузке данных заказа",
    "Chek printerga yuborildi!": "Чек отправлен на принтер!",
    "Chek chiqarishda xatolik": "Ошибка при печати чека",
    "Xizmat haqini yangilashda xatolik: ": "Ошибка при обновлении платы за обслуживание: ",
    "Xizmat haqi saqlandi va chek printerga yuborildi!": "Плата за обслуживание сохранена, и чек отправлен на принтер!",
    "Xatolik yuz berdi": "Произошла ошибка",
    "Admin Boshqaruvi": "Панель Администратора",
    "Buyurtmalar": "Заказы",
    "Menyu (CRUD)": "Меню (CRUD)",
    "Xodimlar": "Сотрудники",
    "Stollar": "Столы",
    "Reytinglar": "Рейтинги",
    "Moliya (Foyda)": "Финансы (Прибыль)",
    "Omborxona": "Склад",
    "Ofitsant Foiz": "Процент официанта",
    "Sozlamalar": "Настройки",
    "Ofitsant Buyurtmalari va Foiz Boshqaruvi": "Заказы официантов и управление процентами",
    "Ofitsantlar": "Официанты",
    "Ofitsant topilmadi": "Официант не найден",
    "Def %:": "По ум. %:",
    "⚡ Aktiv": "⚡ Активные",
    "📋 Tarix": "📋 История",
    "Chap tomondagi ofitsantni tanlang": "Выберите официанта слева",
    "— Aktiv buyurtmalar": "— Активные заказы",
    "Hozircha aktiv buyurtma yo'q": "На данный момент активных заказов нет",
    "Stol №": "Стол №",
    " so'm": " сум",
    " ta boshqa": " других",
    "Hozirgi foiz:": "Текущий процент:",
    "Xizmat haqi %:": "Обслуживание %:",
    "Saqlash": "Сохранить",
    "Saqlash + Chek": "Сохранить + Чек",
    "— Buyurtmalar Tarixi": "— История заказов",
    "← Aktiv ko'rish": "← К активным",
    "Tarix bo'sh": "История пуста",
    "Umumiy buyurtmalar": "Всего заказов",
    "Jami tushum": "Общая выручка",
    "Yopilgan (delivered)": "Закрытые (доставлен)",
    "To'lov:": "Оплата:",
    "💵 Naqd": "💵 Наличные",
    "💳 Karta": "💳 Карта",
    "📱 Click/Payme": "📱 Click/Payme",
    "📒 Nasiya": "📒 В долг",
    "Xizmat haqi:": "Плата за обслуживание:",
    "Moliya va Xarajatlar": "Финансы и Расходы",
    "Yangilash": "Обновить",
    "Umumiy Tushum": "Общая выручка",
    "Umumiy Xarajat": "Общие расходы",
    "Sof Foyda": "Чистая прибыль",
    "To'lov turlari bo'yicha tushum": "Выручка по видам оплат",
    "💵 Naqd pul": "💵 Наличные",
    "💳 Terminal (Karta)": "💳 Терминал (Карта)",
    "📒 Qarzga (Nasiya)": "📒 В долг",
    "Xarajat qo'shish": "Добавить расход",
    "Summa (so'm)": "Сумма (сум)",
    "Mahsulot (Sklad)": "Продукт (Склад)",
    "Oylik maosh": "Зарплата",
    "Arenda (Ijara)": "Аренда",
    "Kommunal to'lovlar": "Коммунальные платежи",
    "Boshqa xarajat": "Другие расходы",
    "Izoh": "Комментарий",
    "Nima uchun ishlatildi?": "Для чего использовалось?",
    "Qo'shish": "Добавить",
    "Xarajatlar tarixi": "История расходов",
    "Sana": "Дата",
    "Xarajatlar yo'q": "Нет расходов",
    "Tizim Sozlamalari": "Настройки системы",
    "Bir martalik idish narxi (so'm)": "Цена одноразовой посуды (сум)",
    "Bir martalik idish mahsulot ID (ma'lumot uchun)": "ID продукта одноразовой посуды (для информации)",
    "* Agar bazada idish uchun yangi mahsulot yaratsangiz, uning ID sini shu yerga yozing.": "* Если вы создаете новый продукт для посуды в базе данных, введите его ID здесь.",
    "Sozlamalarni Saqlash": "Сохранить настройки",
    "Buyurtmalar Monitoringi": "Мониторинг заказов",
    "Mijoz": "Клиент",
    "Jami": "Итого",
    "Holat": "Статус",
    "Amallar": "Действия",
    "Ko'rish": "Просмотр",
    "Xodimlar Reytingi va Ish Sifati": "Рейтинг сотрудников и качество работы",
    "Oshpaz": "Повар",
    "Kuryer": "Курьер",
    "Jami baholar": "Всего оценок",
    "Yaxshi (4-5)": "Хорошо (4-5)",
    "Yomon (1-2)": "Плохо (1-2)",
    "Hali birorta ham xodimga baho berilmagan.": "Пока ни одному сотруднику не была выставлена оценка.",
    "Menyu Boshqaruvi": "Управление меню",
    "Kategoriya": "Категория",
    "Mahsulot": "Продукт",
    "Kategoriyalar": "Категории",
    "Mahsulotlar": "Продукты",
    "Nomi": "Название",
    "Narxi": "Цена",
    "Tannarxi": "Себестоимость",
    "Foyda": "Прибыль",
    "Faol": "Активен",
    "Nofaol": "Неактивен",
    "Kategoriya topilmadi": "Категория не найдена",
    "Tizim mahsuloti, o'chirib bo'lmaydi": "Системный продукт, удаление невозможно",
    "Xodimlar Boshqaruvi": "Управление сотрудниками",
    "Xodim qo'shish": "Добавить сотрудника",
    "Ism": "Имя",
    "Telefon": "Телефон",
    "Vazifa (Role)": "Роль",
    "Stollar Boshqaruvi": "Управление столами",
    "Stol qo'shish": "Добавить стол",
    "Stol Raqami": "Номер стола",
    "Odam soni (Capacity)": "Кол-во человек (Capacity)",
    " kishi": " чел.",
    "Bo'sh": "Свободен",
    "Band": "Занят",
    "Stollar yo'q": "Нет столов",
    "Yangi Xodim": "Новый сотрудник",
    "Ismi Sharif": "ФИО",
    "Parol": "Пароль",
    "Vazifasi": "Роль",
    "Oshpaz (Cook)": "Повар (Cook)",
    "Kuryer (Courier)": "Курьер (Courier)",
    "Ofitsant (Waiter)": "Официант (Waiter)",
    "Yangi Kategoriya": "Новая категория",
    "Rasm yuklash yoki URL": "Загрузить изображение или URL",
    "Yoki to'g'ridan-to'g'ri URL kiriting": "Или введите прямой URL",
    "Foydalanuvchi boshqaruvi (Pors/Dona tanlash)": "Пользовательское управление (Выбор Порц/Шт)",
    "Mahsulotni tahrirlash": "Редактировать продукт",
    "Yangi Mahsulot": "Новый продукт",
    "Tavsif": "Описание",
    "Tanlang...": "Выберите...",
    "O'lchov birligi": "Единица измерения",
    "dona": "шт",
    "pors": "порц",
    "Minimum miqdor": "Мин. количество",
    "Qadam (Step)": "Шаг (Step)",
    "Majburiy idish qo'shish": "Обязательное добавление посуды",
    "Yangi Stol": "Новый стол",
    "Odam soni (Ixtiyoriy)": "Количество человек (Необязательно)",
    "Buyurtma tafsilotlari #": "Детали заказа #",
    "Chekni chiqarish": "Распечатать чек",
    "To'lov turi:": "Тип оплаты:",
    "Manzil / Stol:": "Адрес / Стол:",
    "Ofitsiant:": "Официант:",
    "Noma'lum": "Неизвестно",
    "Mahsulotlar ro'yxati": "Список продуктов",
    "Xizmat haqi foizi (%)": "Процент обслуживания (%)",
    "Qo'llash": "Применить",
    "Saqlash va Chek": "Сохранить и Чек"
}

for uz, ru in replacements.items():
    content = content.replace(uz, ru)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Translation completed for Admin.jsx")
