ALTER TABLE orders ADD COLUMN IF NOT EXISTS service_percentage DECIMAL(5,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS service_fee DECIMAL(12,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(20) DEFAULT '';
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS cost_price DECIMAL(12,2) DEFAULT 0;
