-- Tables jadvaliga vizual joylashuv ustunlari
ALTER TABLE tables ADD COLUMN IF NOT EXISTS pos_x DECIMAL(7,2) DEFAULT 0;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS pos_y DECIMAL(7,2) DEFAULT 0;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS shape VARCHAR(20) DEFAULT 'round';
ALTER TABLE tables ADD COLUMN IF NOT EXISTS width DECIMAL(7,2) DEFAULT 80;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS height DECIMAL(7,2) DEFAULT 80;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS floor INTEGER DEFAULT 1;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS rotation DECIMAL(5,1) DEFAULT 0;
