-- Migration 010: shift_id for orders + idempotency_key for offline sync
-- Date: 2026-07-25

-- 1. Link orders to cashier shifts for financial accountability
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS shift_id INTEGER REFERENCES cashier_shifts(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_orders_shift_id ON orders(shift_id);

-- 2. Idempotency key for offline/PWA order creation
--    Frontend generates a UUID v4; duplicate submissions with the same key are rejected.
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(64);

CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_idempotency_key
    ON orders(idempotency_key)
    WHERE idempotency_key IS NOT NULL;

-- 3. Prevent double stock restoration on cancel
--    Track whether stock has already been restored for a cancelled order.
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS stock_restored BOOLEAN NOT NULL DEFAULT FALSE;

-- 4. Add order_payments unique constraint to prevent double-writes
--    (ON CONFLICT DO NOTHING in code requires this)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_order_payments_order_method'
    ) THEN
        ALTER TABLE order_payments
            ADD CONSTRAINT uq_order_payments_order_method UNIQUE (order_id, method);
    END IF;
END$$;

COMMENT ON COLUMN orders.shift_id IS 'Cashier shift this order belongs to (for X/Z-report accuracy)';
COMMENT ON COLUMN orders.idempotency_key IS 'UUID generated by client for safe offline order re-submission';
COMMENT ON COLUMN orders.stock_restored IS 'TRUE after stock has been restored when order is cancelled';
